config/routes.rb
Rails.application.routes.draw do

root to: 'articles#index'

resources :articles do
	resources :comments
end
resources :tags

resources :authors

resources :attachments

resources :author_sessions, only: [ :new, :create, :destroy ]

get 'login' => 'author_sessions#new'

get 'logout' => 'author_sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base


	mount_uploader :attachment, AttachmentUploader
	
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	#has_attached_file :image

	#this was from paperclip
	#validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"]}



def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end

def tag_list

  self.tags.collect do |tag|
    tag.name
  end.join(", ")
  
end


end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper

before_filter :require_login, except: [:show, :index]

def index

	@articles = Article.all

end

def show

	@article = Article.find(params[:id])

	@comment = Comment.new

	@comment.article_id = @article.id


end

def new

	@article = Article.new

	
end

def create

	@article = Article.new(article_params)	

	@article.save

	flash.notice = "Article '#{@article.title}' Created!"

	redirect_to article_path(@article)

end

def tag_list=(tags_string)
end

def destroy

	@article = Article.find(params[:id])

	@article.destroy

	flash.notice = "Article '#{@article.title}' Destroyed!"
	
	redirect_to '/articles/'

end

def edit

	@article = Article.find(params[:id])

end

def update

	@article = Article.find(params[:id])
	@article.update(article_params)

	flash.notice = "Article '#{@article.title}' Updated!"

	redirect_to article_path(@article)
end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
end

  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :require_login, except: [:create]

def create
	
	@comment = Comment.new(comment_params)
	@comment.article_id = params[:article_id]

	@comment.save

	redirect_to article_path(@comment.article)
end

def comment_params
	
	params.require(:comment).permit(:author_name, :body)

end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

before_filter :require_login, only: [:destroy]

def show
	@tag = Tag.find(params[:id])

end

def index
	@tag = Tag.all
end

def destroy

	@tag = tag.find(params[:id])

	@tag.destroy

	flash.notice = "Tag '#{@tag.title}' Destroyed!"
	
	redirect_to '/tags/'

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

def article_params	
	params.require(:article).permit(:title, :body, :tag_list, :attachment , :attachment_cache, :remove_attachment )
end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
	<h4>Comment by <%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
	


	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<%end %>
	</ul>

<div class="container">

	<div class="row">
		<div class="col-md-6">
		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
		</div>
	</div> <!-- title row -->

	<div class="row">
		<div class="col-md-6">
			<p>
				<%= f.label :body %><br />
				<%= f.text_area :body %>
			</p>
		</div>
		<div class="col-md-6">
			<p>

	 		 <%= f.file_field :attachment%>
	 		 <%= f.label :attachment, "Attach a New Image" %>
	 		 <%= attachment_tag (@article.attachment_url) if @article.attachment? %>	  
	 		 <%= f.hidden_field :attachment_cache %>
	  
			</p>
		</div>	
	</div> <!-- body row -->

	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<ul class="nav nav-pills">
				<li role="presentation" class="active">
					<label>
					<%= f.check_box :remove_attachment %> Remove image
					</label>
				</li>
				<li role="presentation" class="active">
					<%= f.label :tag_list %> 
					<%= f.text_field :tag_list %>
				</li>
			</ul>
		</div>
		<div class="col-md-2"></div>
	</div> <!-- finishing touches row -->

<div class="row">
<div class="col-md-2 "><%= f.submit %></div>
</div>

</div> <!-- container -->
<% end %>

app/views/articles/edit.html.erb
<h1> </h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<div class="jumbotron">
  	<h1>Hello, I'm John</h1>
  	<p>Please hire me</p>
  	<p><a class="btn btn-primary btn-lg" href="#" role="button">Resume</a></p>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2"></div>
		<div style=" background-color:#000000">k</div><div style="background-color: #062F4F">k</div><div style="background-color: #813772">k</div><div style="background-color: #B82601">k</div>
		<h1>All Posts</h1>
		<br/>
		<div class="col-md-2"></div>
	</div> <!-- header row -->



<div class="row" id="articles">
		<div class="col-md-2"></div>
	<% @articles.each do |article| %>
		<div class=" col-xs-8 col-md-2" id="posts">
			<h3 id="attachment_thumb">
			<%= image_tag article.attachment.url(:thumb) if article.attachment? %>
			<%= link_to article.title, article_path(article), 
				class: 'article_title', id: "article_#{article.id}" %>
			</h3>
		</div>
	<% end %>
		<div class="col-md-2"></div>
</div>
<br/>
</div><!-- container -->

<div class=container-fluid">
	<div class="row" id="offset">

		<div class="btn btn-secondary">
			<% if logged_in? %>
			<%= link_to "Create a New Article", new_article_path, class:"new_article" %>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="page-header">
<h1> Edit Article </h1>
</div>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<div class="container fluid-container">

	<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="col-md-8">
			<h1><%= @article.title %></br></h1>
			<h4>
					<%= @article.tags.each do |tag| %>
						<%= link_to tag.name, tag_path(tag) %>
					<% end %>
			</h4>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>
</div>
<div >
			
		<div id="wrapper" style="width:100%; text-align:center">
				<%= image_tag @article.attachment.url(:jumbo) if @article.attachment? %>
		</div>
</div>
<div class="container fluid-container">

	<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		<div class="col-md-8">
		<br/>
		<div>
			<p>
				<%= @article.body %>
			</p>
		</div>
		<div>
			<ul class="nav nav-pills" id="options">
				<li role="presentation" class="active"><%= link_to "Back.", articles_path %></li>
				<li role="presentation" class="active">
					<% if logged_in? %>
					<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
					<% end %>
				</li>
				<li role="presentation" class="active">
					<% if logged_in? %>
					<%= link_to "edit", edit_article_path(@article)%>
					<% end %>
				</li>
			</ul>
		</div>
		<div>
		<%= render partial: 'comments/form' %>
		</div>
		<div>
		<h3>Comments (<%= @article.comments.size %>)</h3>
		</div>
		<div>
		<%= render partial: 'articles/comment', collection: @article.comments.reverse %>
		</div>
	</div>
	<div class="col-md-2"></div>
	</div> <!-- the shit -->


</div>

app/views/author_sessions/new.html.erb
<%= form_tag author_sessions_path, method: :post do %>
  

    <%= label_tag :email %>
    <%= text_field_tag :email %>
    

  

  

    <%= label_tag :password %>
    <%= password_field_tag :password %>
    

  

  

    <%= submit_tag "Login" %>
  

<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>



<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.image %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @image.image %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jfk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    

<meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">

  </head>

  <body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="btn btn-default navbar-btn" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
	MENU
      </button>

      <a class="navbar-brand" href="/articles">JFK.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/articles">Posts <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Pictures</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Music</a></li>
            <li><a href="#">Art</a></li>
            <li><a href="#">Literature</a></li>
          </ul>
        </li>
      </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


    <p class="flash">
    <%= flash.notice %>
  </p>
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</br>
    <div class="row">
		<div class="col-md-12">
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
      </h6>
    </div>
  </div>

  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
	<% @tag.each do |tag| %>
		<li>
			<%= link_to tag.title, article_path(article) ,
		class: 'tag_title', id: "tag_#{tag.id}" %>
				
		</li>
	<% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class:"new_article" %>

app/views/tags/show.html.erb
<div class="container">
	<div class="page-header">
		<h1>Articles Tagged with <%= @tag.name %></h1>
	</div>

	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<ul>
				<% @tag.articles.each do |article| %>
	   			<li><%= link_to article.title, article_path(article) %></li>
				<% end %>
			</ul>
		</div>
		<div class="col-md-2"></div>
	</div>
</div>